import type { NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";
import { APP_NAME } from "../utils/consts";

import Heading from "../components/Heading";
import Book from "../components/Book";
import Layout from "../layouts/Layout";

const HomePage: NextPage = () => {
  const books = trpc.book.getBooks.useQuery();

  if (books.isLoading) return <p>Loading...</p>;
  if (books.isError || !books.data) {
    console.error(books.error);
    return <p>Error</p>;
  }
  return (
    <Layout>
      <Head>
        <title>{APP_NAME}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading priority={1}>{APP_NAME}</Heading>

      {books.data.length > 0 && (
        <ul className="flex flex-col gap-y-4">
          {books.data.map((book) => (
            <Book key={book.id} book={book} />
          ))}
        </ul>
      )}
    </Layout>
  );
};

export default HomePage;
