import type { NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";
import { APP_NAME } from "../utils/consts";

import Book from "../components/Book";
import BookForm from "../widgets/BookForm";

const Home: NextPage = () => {
  const books = trpc.book.getBooks.useQuery();

  if (books.isLoading) return <p>Loading...</p>;
  if (books.isError || !books.data) {
    console.error(books.error);
    return <p>Error</p>;
  }
  return (
    <>
      <Head>
        <title>{APP_NAME}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700">
          {APP_NAME}
        </h1>

        <div className="flex w-full items-center justify-center pt-6">
          {books.data.length > 0 && (
            <ul className="flex flex-col gap-y-4">
              {books.data.map((book) => (
                <Book key={book.id} book={book} />
              ))}
            </ul>
          )}
        </div>
        <BookForm action="add" />
      </main>
    </>
  );
};

export default Home;
